TROVE_ZOTERO_MAPPINGS = {
	'Art work': 'artwork',
	'Article': 'journalArticle',
	'Article/Book chapter': 'bookSection',
	'Article/Conference paper': 'conferencePaper',
	'Article/Journal or magazine article': 'journalArticle',
	'Article/Other article': 'journalArticle',
	'Article/Report': 'report',
	'Article/Review': 'journalArticle',
	'Article/Working paper': 'report',
	'Audio book': 'book',
	'Book': 'book',
	'Book/Braille': 'book',
	'Book/Illustrated': 'book',
	'Book/Large print': 'book',
	'Conference Proceedings': 'book',
	'Data set': 'computerProgram',
	'Map': 'map',
	'Map/Aerial photograph': 'map',
	'Map/Atlas': 'map',
	'Map/Braille': 'map',
	'Map/Electronic': 'map',
	'Map/Globe or object': 'map',
	'Map/Large print': 'map',
	'Map/Map series': 'map',
	'Map/Microform': 'map',
	'Map/Single map': 'map',
	'Object': 'artwork',
	'Periodical': 'book',
	'Periodical/Journal, magazine, other': 'book',
	'Periodical/Newspaper': 'book',
	'Photograph': 'artwork',
	'Poster, chart, other': 'artwork',
	'Published': 'document',
	'Sheet music': 'document',
	'Sound': 'audioRecording',
	'Sound/Interview, lecture, talk': 'audioRecording',
	'Sound/Other sound': 'audioRecording',
	'Sound/Recorded music': 'audioRecording',
	'Thesis': 'thesis',
	'Unpublished': 'manuscript',
	'Video': 'videoRecording',
	'Video/Captioned': 'videoRecording'
}

FIELD_MAPPINGS = {
	#Not including common fields that have multiple values
	# contributor -> creator
	# tags -> tags
	# subject -> tags
	'journalArticle': { 
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'publicationTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'pagination': 'pages',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'book': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'publisher',
		'edition': 'edition',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'bookSection': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'bookTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'pagination': 'pages',
		'publisher': 'publisher',
		'edition': 'edition',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'conferencePaper': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'proceedingsTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'pagination': 'pages',
		'publisher': 'publisher',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'report': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'institution',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'thesis': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'university',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'artwork': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'map': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'publisher',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'computerProgram': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'abstract': 'abstractNote',
		'publisher': 'company',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'document': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'publisher',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'manuscript': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'language': 'language',
		'abstract': 'abstractNote',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'audioRecording': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'seriesTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'label',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'videoRecording': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'seriesTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'studio',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'encyclopediaArticle': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'encyclopediaTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'publisher': 'publisher',
		'repository': 'archive',
		'rights': 'rights',
		'source': 'libraryCatalog'
	},
	'webpage': {
		'title': 'title',
		'troveUrl': 'url',
		'issued': 'date',
		'isPartOf': 'websiteTitle',
		'language': 'language',
		'abstract': 'abstractNote',
		'rights': 'rights'
	}
}